name: test

on:
  workflow_dispatch:
  # run when a release has been created
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: "windows-2022"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to release
        # upload the generated wheels to the github release
        uses: sqlalchemyorg/upload-release-assets@sa
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'time.md'