name: test

on:
  workflow_dispatch:


# env:
  # comment TWINE_REPOSITORY_URL to use the real pypi. NOTE: change also the secret used in TWINE_PASSWORD
  # TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

jobs:
  release:
    name: Release
    if: github.actor == 'CaselIT' || github.actor == 'zzzeek'
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set version
        run: |
          python -c 'import datetime; open("time.md", "w").write(datetime.datetime.utcnow().isoformat())'

      - name: Commit version change
        uses:  sqlalchemyorg/git-auto-commit-action@sa
        with:
          commit_message: test
          file_pattern: time.md
